version: "3"
services:
  app:
    build: ./app
    ports:
      - 8081:8080
    networks:
      - net

  api:
    build: ./api
    ports:
      - 8080:3000
    networks:
      - net
    environment:
      - CONNECTION_STRING=postgresql://test:test@database/test
      - NODE_ENV=production

  database:
    build: ./db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    networks:
      - net
  
networks:
  net:

volumes:
  db: